// Generated by CoffeeScript 1.9.2
var deep;

deep = function(i) {
  return JSON.parse(JSON.stringify(i));
};

module.exports = {
  stringify: function(grammar) {
    var escape, expression, expressions, production;
    escape = function(text) {
      return text.replace(/\\/g, '\\\\').replace(/\"/g, '\"').replace(/\n/g, '\\n').replace(/\t/g, '\\t');
    };
    expression = function(e) {
      var exp, res;
      res = (function() {
        var j, len, results;
        results = [];
        for (j = 0, len = e.length; j < len; j++) {
          exp = e[j];
          if (exp.nt != null) {
            results.push(exp.nt);
          } else {
            results.push("\"" + (escape(exp.t)) + "\"");
          }
        }
        return results;
      })();
      return res.join(' ');
    };
    expressions = function(e) {
      var exp, res;
      res = (function() {
        var j, len, results;
        results = [];
        for (j = 0, len = e.length; j < len; j++) {
          exp = e[j];
          results.push(expression(exp));
        }
        return results;
      })();
      return "" + (res.join(', '));
    };
    production = function(e) {
      var exp, res, term;
      res = (function() {
        var results;
        results = [];
        for (term in e) {
          exp = e[term];
          results.push(term + " -> " + (expressions(exp)));
        }
        return results;
      })();
      return res.join('\n');
    };
    return production(grammar);
  },
  convert: function(grammar, root) {
    var cnf, i, index, j, k, key, l, len, len1, len2, len3, len4, m, n, o, ref, ref1, replace, replacementrule, rule, rules, term;
    cnf = deep(grammar);
    index = 0;
    cnf["$" + root] = deep(cnf[root]);
    replace = function(source, target) {
      var key, results, rule, rules, term;
      results = [];
      for (key in cnf) {
        rules = cnf[key];
        results.push((function() {
          var j, len, results1;
          results1 = [];
          for (j = 0, len = rules.length; j < len; j++) {
            rule = rules[j];
            results1.push((function() {
              var k, len1, results2;
              results2 = [];
              for (k = 0, len1 = rule.length; k < len1; k++) {
                term = rule[k];
                if ((term.nt != null) && term.nt === source) {
                  results2.push(term.nt = target);
                } else {
                  results2.push(void 0);
                }
              }
              return results2;
            })());
          }
          return results1;
        })());
      }
      return results;
    };
    ref = cnf["$" + root];
    for (j = 0, len = ref.length; j < len; j++) {
      rule = ref[j];
      rule.push({
        nt: '$'
      });
    }
    replace(root, "$" + root);
    for (key in cnf) {
      rules = cnf[key];
      for (k = 0, len1 = rules.length; k < len1; k++) {
        rule = rules[k];
        if (rule.length > 1) {
          for (l = 0, len2 = rule.length; l < len2; l++) {
            term = rule[l];
            if (term.t != null) {
              cnf["Lone" + index] = [
                [
                  {
                    t: term.t
                  }
                ]
              ];
              delete term.t;
              term.nt = "Lone" + index;
              index++;
            }
          }
        }
      }
    }
    for (key in cnf) {
      rules = cnf[key];
      for (m = 0, len3 = rules.length; m < len3; m++) {
        rule = rules[m];
        if (rule.length > 2) {
          replacementrule = [
            rule[0], {
              nt: "Simple" + index
            }
          ];
          index++;
          for (i = n = 1, ref1 = rule.length - 2; 1 <= ref1 ? n < ref1 : n > ref1; i = 1 <= ref1 ? ++n : --n) {
            cnf["Simple" + (index - 1)] = [
              [
                rule[i], {
                  nt: "Simple" + index
                }
              ]
            ];
            index++;
          }
          cnf["Simple" + (index - 1)] = [[rule[rule.length - 2], rule[rule.length - 1]]];
          while (rule.length > 0) {
            rule.pop();
          }
          for (o = 0, len4 = replacementrule.length; o < len4; o++) {
            term = replacementrule[o];
            rule.push(term);
          }
        }
      }
    }
    for (key in cnf) {
      rules = cnf[key];
      if (rules.length !== 1 || rules[0].length !== 1 || (rules[0][0].nt == null)) {
        continue;
      }
      replace(key, rules[0][0].nt);
      delete cnf[key];
    }
    return cnf;
  }
};
