// Generated by CoffeeScript 1.9.2
var bnf, cnf, grammar;

bnf = require('./bnf');

cnf = require('./cnf');

grammar = bnf.parse("list = \"<\" items \">\";\nitems = items \" \" item | item;\nitem = \"a\" | \"b\" | \"c\";");

grammar = cnf.convert(grammar, 'list');

console.log('-----------------------------');

console.log(cnf.stringify(grammar));
