// Generated by CoffeeScript 1.9.2
var bnf, cnf, cyk, parser;

bnf = require('./bnf');

cnf = require('./cnf');

cyk = require('./cyk');

parser = cyk.generate(cnf.convert('list', bnf.parse("list = \"<\" items \">\";\nitems = items \" \" item | item;\nitem = \"a\" | \"b\" | \"c\";")));

console.log('-----------------------------');

console.log(parser('<a>'));
